name: Setup Python Environment
description: Sets up a Python environment with Poetry and GDAL dependencies.

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build tools
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          libgeos-dev \
          libproj-dev

    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}

    - name: Configure Poetry
      run: poetry config virtualenvs.in-project true

inputs:
  python-version:
    required: true
    description: The Python version to use.
  poetry-version:
    required: true
    description: The Poetry version to install.
