name: Python Style Checker

on: [push, pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v2

      # Use the custom action to set up the Python environment
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-environment
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: '1.6.1'

      # Cache style dependencies (e.g., Black)
      - name: Cache Black Installation
        id: cache-black
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-black-${{ matrix.python-version }}

      # Install Black if it's not already cached
      - name: Install Style Checker
        run: poetry add --dev black
        if: steps.cache-black.outputs.cache-hit != 'true'

      # Lint with Black
      - name: Lint with Black
        run: poetry run black --check .
        continue-on-error: true
